### ISSUE TITLE
MSC-Builder: LaBr3 addresses

### ISSUE THREAD

**Issue by AdamGarnsworthy** [GRIFFINCollaboration/griffinMarkII#101]
When DS LaBr3 only selected: 
In group 1: The channel number of the shields (LBS01AN00X) should start at 4 but starts at 0.

When US LaBr3 only selected: Only 1 entry in each table appears.

When US and DS LaBr3 selected:
In group 1: The channel number of the shields (LBS01AN00X) should start at 4 but starts at 0.

In group 2: The channel number of the LaBr3 E (LBL05XN00X) should start at 0 but starts at 4.

In group 2: The channel number of the shields (LBS05AN00X) should start at 4 but starts at 12.

**Comment by rishitagudapati** [comment]
Hi Adam, these issues should have been fixed with the latest commit already. Please try a hard refresh on your browser and let me know if the issues persist. Thanks.

**Comment by AdamGarnsworthy** [comment]
Yes, looks good now thanks!
