### ISSUE TITLE
Filter list

### ISSUE THREAD

**Issue by SmithJK** [GRIFFINCollaboration/griffinMarkII#56]
List of filters is not showing up when using Firefox 43.0.4 on Ubuntu. It should be a drop-down box next to Load/Delete Filter with the list of filters shown in the ODB (/Filter/Filters)
![screenshot from 2016-01-26 13 24 30](https://cloud.githubusercontent.com/assets/10604745/12595452/394dee2c-c430-11e5-8039-a2b7089f3ab7.png)
![screenshot from 2016-01-26 13 25 24](https://cloud.githubusercontent.com/assets/10604745/12595492/6711043e-c430-11e5-8a48-e9a0e8bb616c.png)

**Comment by katieannemills** [comment]
Neat, thanks - this is all getting rebuilt presently, all these little UI quirks will go away at v3.

**Comment by katieannemills** [comment]
seems resolved in v3!
