### ISSUE TITLE
shack monitor

### ISSUE THREAD

**Issue by katieannemills** [GRIFFINCollaboration/griffinMarkII#60]
The Equipment/Agilent34970A record in GRIFFIN's ODB has gone away; this was where we were reporting shack temperatures ala Lisa's student project from a couple years ago, ingested by the dashboard's shack monitor. Is this gone because we don't want it anymore, gone by mistake, or gone but replaced with something else?

cc @AdamGarnsworthy @SmithJK

**Comment by SmithJK** [comment]
Was it on grsmid00 before? I see it on grifsoh00 right now.

**Comment by katieannemills** [comment]
Oh yeah, it was on a different experiment, I forgot about that - but I see you've turned on security there. While I am a big big fan of more security on our experiments, I vaguely remember there being some authentication issues in automated processes (issues like, 'you can't'). Anyway, I'll look into it and open a different issue if it's actually a problem. Thanks!
