### ISSUE TITLE
Expand list of detector types

### ISSUE THREAD

**Issue by SmithJK** [GRIFFINCollaboration/griffinMarkII#61]
Please expand the list of detector types available for the filter. The current list of detector types is given in Table 5.4 here: https://rawgit.com/wiki/GriffinCollaboration/GRSISort/technical-docs/GRIFFIN_Event_Format.pdf

**Comment by katieannemills** [comment]
Not a problem on my end, but this will necessitate changing the filter logic encoding in the ODB - 'GR-S-1' doesn't make sense with two griffin triggers, for example. Make sure Chris (and anyone else who goes looking at the `/Filter` ODB directory knows how to read these.

**Comment by SmithJK** [comment]
Instead of directly writing a two-digit detector number to the ODB for the detector system, let's use the short names in the table.

This will be fine from the "frontend reading the ODB" perspective - Chris and I just tested variable length strings for the subsystems.

**Comment by katieannemills** [comment]
The short names aren't all unique - see ID 10 and 11.

**Comment by SmithJK** [comment]
Fair point - let's go with DSCn and DSCg for those.

**Comment by SmithJK** [comment]
Or, more accurately, DSCg and DSCn for DESCANT gamma and DESCANT neutron, respectively.
