### ISSUE TITLE
first viable v3 candidate available

### ISSUE THREAD

**Issue by katieannemills** [GRIFFINCollaboration/griffinMarkII#64]
Hi folks - a feature-complete first pass at v3 is now available at http://griffincollaboration.github.io/griffin-dashboard/griffin.html
- This ought to resolve #57 and #61 
- all design goals have been met - 100% client side logic, better responsiveness and smoother UI.
- ~~The price of 100% client-side is slightly slower load times; I might be able to speed things up in Chrome, at the cost of dropping firefox support, which I wouldn't recommend - supporting only one sole solitary browser is a bit risky. FF will _eventually_ get right with html imports, at which time it'll be just as smooth - I would wait it out.~~ **Edit** actually, it was the drawing framework that was slowing things down, after all; should be fixed in #71

I'm going to go implement everyone's suggestions on the Toolkit while you have a look around here - as always, let me know any requests or problems.

**Comment by SmithJK** [comment]
When there is no EnabledDetectorType key in the ODB Filter, select all detector systems as enabled.

EnabledDetectorType should have an "ALL" option.

Otherwise, EnabledDetectorType will be an array of strings, with the short string value for each enabled detector subsystem.

**Comment by katieannemills** [comment]
@SmithJK  mmmk, implemented; except in hindsight, the 'ALL' key isn't necessary; why not just have an array with everything and avoid the special case? We originally considered 'ALL' when we were going to jam this all into one string and were worried about having a super long string, which isn't an issue if this key is an array.

**Comment by SmithJK** [comment]
It's still using the two-letter detector name strings rather than the three-or-four-letter detector type string names. For example, "GR" is used instead of "GRGa" and "GRGb".

**Comment by katieannemills** [comment]
oh in `EnabledDetTypes`, right, sorry - but could you refresh my memory on what exactly this key does? If the obvious assumption is true (it enables detector types so they can participate in the filter), why do we need a special UI block for it - why not just infer it from the filter definition? (to clarify: we can keep the `EnabledDetTypes` key in the ODB for Chris - I'm talking about the separate UI element; seems redundant unless I've misunderstood what the point of `EnabledDetTypes` is).

**Comment by SmithJK** [comment]
It's for incidental data.
If, for example, we have GRIFFIN and SCEPTAR and want to use a HPGe coincidence trigger, we might still want to keep the SCEPTAR events that are also within the event window. Or we might not.

**Comment by katieannemills** [comment]
Right you are - should be behaving better now.
