### ISSUE TITLE
LaBr in the MSC Builder

### ISSUE THREAD

**Issue by SmithJK** [GRIFFINCollaboration/griffinMarkII#75]
The LaBr detectors aren't included in the MSC Builder page.

**Comment by SmithJK** [comment]
Scratch that. These are included in the GRIFFIN+DANTE button, but it should say GRIFFIN+LaBr instead.

**Comment by katieannemills** [comment]
What about more broadly? Should the detector views be titled LaBr3 instead of DANTE?

**Comment by SmithJK** [comment]
Yep.

**Comment by SmithJK** [comment]
I'm fixing the labels on the Builder right now... because I realized I can.

**Comment by SmithJK** [comment]
The first issue here has been resolved. @BillMills, do you want to leave the issue open until the detector views are updated as well?

**Comment by SmithJK** [comment]
Related question - is the MSC Builder from this repo expected to have "Write to ODB" functionality?

**Comment by katieannemills** [comment]
Does it not write to the odb yet? Yeah, I left a lot of that not plugged in as so not to blow up the ODB before we were sure we wanted it - I'll hook that up probably today.

**Comment by SmithJK** [comment]
Excellent. That functionality will make it easier to set-up for the tests Bruno wants to do this week.

**Comment by katieannemills** [comment]
@SmithJK Now that I actually look at this, it _should_ be writing to `/DAQ/MSC/whatever` on `grsmid00.triumf.ca:8081` already - does it not do that when you try?

**Comment by SmithJK** [comment]
Nope.

**Comment by SmithJK** [comment]
Accessed here: http://griffincollaboration.github.io/griffin-dashboard/msc-builder.html
With Google Chrome Version 27.0.1453.110

**Comment by SmithJK** [comment]
It could be that there's a lag, but it's still not over-writing the ODB.

If it overwrites successfully, is there any user feedback on the dashboard itself? Some text appearing, the button changing color, or the page reloading?

**Comment by katieannemills** [comment]
That would be nice, but unfortunately the way MIDAS handles its response headers means we can't check for the usual `200 OK` - y'all need to put proper [CORS headers](http://enable-cors.org/) on things you want to be interoperable. That said, we could do a whole other round trip to read back from the ODB and compare to what we asked for - I'll look into that today.

Anyway - your chrome is too old. I just overwrote the MSC table a couple of times from Chrome 50.0.2661.102, but anything >29 should be ok.

**Comment by SmithJK** [comment]
_grumbling about old operating systems that don't run the latest versions_

It works on Firefox.

It also includes the suppressor channels (DAS). @AdamGarnsworthy, will we have suppressors around these at a future point? Is it worth allowing tick boxes for LaBr and Suppressors just like we now have for Griffin?

**Comment by SmithJK** [comment]
Is it worth it (and possible) to have some warning that a user's browser won't work with this page?

**Comment by katieannemills** [comment]
Let me know if the browser detection and update integrity checking seem to be working, and if you want those optional suppressors on the labr3.

**Comment by SmithJK** [comment]
The browser detection works. I'll verify the integrity checking later in the week when it won't be as disruptive.

**Comment by AdamGarnsworthy** [comment]
Yes we will have suppressors.

On 20 June, 2016 11:05:43 AM PDT, SmithJK notifications@github.com wrote:

> _grumbling about old operating systems that don't run the latest
> versions_
> 
> It works on Firefox.
> 
> It also includes the suppressor channels (DAS). @AdamGarnsworthy, will
> we have suppressors around these at a future point? Is it worth
> allowing tick boxes for LaBr and Suppressors just like we now have for
> Griffin?
> 
> ---
> 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/GRIFFINCollaboration/griffin-dashboard/issues/75#issuecomment-227221378

## 

Sent from my Android device with K-9 Mail.

**Comment by AdamGarnsworthy** [comment]
Suppressors for LaBr3 will start arriving in 2017.
-What would be super useful for this feature would be if we can customize the MSC table produced at the S level - the equivalent of taking the mini-SAS connector for that GRIF-16 and plugging it in somewhere else.

**Comment by AdamGarnsworthy** [comment]
Where do I find the link for this on the dashboard these days?

**Comment by katieannemills** [comment]
@AdamGarnsworthy re: customization: why not master channel, too? (but not adc channel - that's no better than just doing it from the odb).

**Comment by AdamGarnsworthy** [comment]
-In the old version I thought it printed it to the screen for you to check first before writing to ODB. At that point I am suggesting we add customization options. However it seems to just write, hence next point. 
-We need protection from accidentially writting to the ODB (like I think I just did). Analogous to the way the gain-matcher checks with you to make sure you are super sure you want to actually write to the values to the ODB.

**Comment by katieannemills** [comment]
Sure, we could do a pre-clearance check with options to customize things, which would necessarily put an 'are you sure' in between the ODB and a single misfired click - probably doable by mid-weekish.
