### ISSUE TITLE
MSC Builder should set data type

### ISSUE THREAD

**Issue by SmithJK** [GRIFFINCollaboration/griffinMarkII#82]
...please.

**Comment by katieannemills** [comment]
Sure can.

**Comment by katieannemills** [comment]
so but - I take it this means you need a toggle for whether griffin detectors are low gain or high gain. Should this be per position, per ADC channel, universal for the whole array...?

**Comment by katieannemills** [comment]
also the table I'm using for this looks lke:

| Detector index | Detector Type |
| --- | --- |
| 0 | GRIFFIN Low Gain |
| 1 | GRIFFIN High Gain |
| 2 | SCEPTAR |
| 3 | LaBr3 (Energy) |
| 4 | LaBr3 (Time) |
| 5 | PACES |
| 6 | DESCANT |
| 7 | GRIFFIN Suppressors |
| 8 | LaBr3 Suppressors |
| 9 | ZDS |

Note the absence of SPICE and its S2/S3 sidekicks.
