### ISSUE TITLE
MSC Builder addresses

### ISSUE THREAD

**Issue by SmithJK** [GRIFFINCollaboration/griffinMarkII#83]
Is it possible that in the new upgrade to the MSC Builder, the addresses were switched from being written as 16-bits to being written as 32-bits?

**Comment by katieannemills** [comment]
It's very possible - where would you like those extra 16 bits?

**Comment by SmithJK** [comment]
The addresses are only 16 bits long.

**Comment by katieannemills** [comment]
Oh sorry, I misunderstood your original post - I thought you were _asking_ for that to happen, but now I see you're speculating it already did. 

They shouldn't be, but anything's possible - what looks off to you?

**Comment by SmithJK** [comment]
We read off all the addresses and they spilled over into the next channel, so we were seeing addresses of 0,0,1,0,2,0,3,0,4,... instead of 0,1,2,3,4... We fixed this by making the addresses bigger.

Also, it looks like the size of the items in the MSC array is 4 bytes.

**Comment by SmithJK** [comment]
Not sure if these were 2 or 4 before.

**Comment by katieannemills** [comment]
~~MSC addresses are always 4 bytes. One for M, one for S, and two for C, in that order of decreasing significance. Does that resolve this problem?~~

**Comment by katieannemills** [comment]
Or ha wait no they're always 2 bytes - 4 hex digits, 2 bytes. Sorry - I'm just unclear on what exactly you want to have happen here - let me know.

**Comment by katieannemills** [comment]
Per our discussion today, we'll go to an array of shorts in the ODB for the MSC table, so y'all can read 16 bits at a time like you were doing originally.
