### ISSUE TITLE
PPG Cycle builder doesn't read back newly created cycle

### ISSUE THREAD

**Issue by SmithJK** [GRIFFINCollaboration/griffinMarkII#85]
Cd-cycle as an example. We created the cycle, changed the name in the text box, then clicked "Save Cycle Definition". It saved a cycle definition with the correct time lengths, but not with the correct PPG patterns (as viewed in the ODB).

Also, when I tried to load the cycle, it doesn't show any cycle steps.

(I fixed the PPG patterns by hand.)

**Comment by katieannemills** [comment]
wow this was terrible on a number of fronts - there's a patch ready to merge in #86, but as I note there, we need to change the capitalization of some of the directories in the PPG ODB directory - let me know if I can go ahead and do that, and then we should be good to go.
