### ISSUE TITLE
SCEPTAR channel labeling seems wrong

### ISSUE THREAD

**Issue by katieannemills** [GRIFFINCollaboration/griffinMarkII#92]
The labeling of SCEPTAR channels seems all wrong - if I recall, the lower numbers (SEP01-SEP05) should be the inner ring of the downstream half, increasing with phi - both of which requirements are [currently exactly backwards](http://griffincollaboration.github.io/griffin-dashboard/sceptar.html). @AdamGarnsworthy can you please review the current labeling at the link above and let me know how it looks.

**Comment by AdamGarnsworthy** [comment]
Upstream ones are correct.
Downstream ones have inner and outer rings switched.
1-6
2-7
3-8
4-9
5-10
